version: '3.1'

services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wp_admin
      MYSQL_PASSWORD: cicd1234
      MYSQL_ROOT_PASSWORD: cicd1234
    volumes:
      - db_data:/var/lib/mysql  

  db_redis:
    image: redis:7.4.2
    # command: redis-server --apendonly yes
    ports:
      - "6379:6379"
    restart: always  

volumes:
  db_data: