version: '3.1'

services:
  wordpress:
    image: wordpress:php8.3-apache
    # command: >
    #   sh -c "
    #   if [ ! -f /usr/local/bin/wp ]; then
    #     curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar &&
    #     chmod +x wp-cli.phar &&
    #     mv wp-cli.phar /usr/local/bin/wp;
    #   fi &&
    #   exec apache2-foreground
    #   "
    ports:
      - "8000:80"
      - "44300:443"
    volumes:
      - ./wp-config.php:/var/www/html/wp-config.php
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-cli.phar:/usr/local/bin/wp
    # environment:
    #   WORDPRESS_DB_HOST: db
    #   WORDPRESS_DB_USER: wp_admin
    #   WORDPRESS_DB_PASSWORD: cicd1234
    #   WORDPRESS_DB_NAME: wordpress_db
    depends_on:
      - db
      - db_redis

  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wp_admin
      MYSQL_PASSWORD: cicd1234
      MYSQL_ROOT_PASSWORD: cicd1234
    volumes:
      - db_data:/var/lib/mysql  

  db_redis:
    image: redis:7.4.2
    # command: redis-server --apendonly yes
    ports:
      - "6379:6379"
    restart: always  

volumes:
  db_data: