---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: "ap-northeast-2a"
      containers:
      - name: mysql
        image: mysql:8.0
        args:
        - "--max_connections=2000"
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: "wordpress_db"
        - name: MYSQL_USER
          value: "wp_admin"
        - name: MYSQL_PASSWORD
          value: "cicd1234"
        - name: MYSQL_ROOT_PASSWORD
          value: "cicd1234"
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"

      # - name: node-exporter
      #   image: prom/node-exporter
      #   ports:
      #   - containerPort: 9100   
      #   resources:
      #     requests:
      #       cpu: "100m" 
      #     limits:
      #       cpu: "500m"  

      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: mysql
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mysql
  # - port: 9100
  #   targetPort: 9100
  #   name: node-exporter      
  selector:
    app: mysql

