---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox
        command: ['sh', '-c', 'until nc -z db 3306; do echo waiting for db; sleep 2; done;']
      - name: wait-for-redis
        image: busybox
        command: ['sh', '-c', 'until nc -z redis 6379; do echo waiting for redis; sleep 2; done;']
      containers:
      - name: wordpress
        image: sincerejisoo/wordpress-k8s:latest
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          requests:
            cpu: "1"    # min 0.5 vCPU
            memory: "2Gi" # max 512 MiB memory
          limits:
            cpu: "2"       # min 1 vCPU
            memory: "4Gi"  # max 1 GiB memory
        volumeMounts:
        - name: wp-content
          mountPath: /var/www/html/wp-content

      # - name: node-exporter
      #   image: prom/node-exporter
      #   ports:
      #   - containerPort: 9100    
      #   resources:
      #     requests:
      #       cpu: "100m" 
      #     limits:
      #       cpu: "500m" 
      volumes:
      - name: wp-content
        persistentVolumeClaim:
          claimName: wp-content-pvc    
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: https
  # - port: 9100
  #   targetPort: 9100
  #   name: node-exporter  
  selector:
    app: wordpress

