apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
specs:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:php8.3-apache
          env:
            - name: DB_HOST_KUB
              value: "auth-service.default"
      volumes:
        - name: wp-config
          hostPath:

