---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: 130831355352.dkr.ecr.ap-northeast-2.amazonaws.com/wpproj/wordpress:latest
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          requests:
            cpu: "500m"    # min 0.5 vCPU
            memory: "512Mi" # max 512 MiB memory
          limits:
            cpu: "1"       # min 1 vCPU
            memory: "1Gi"  # max 1 GiB memory
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: https
  selector:
    app: wordpress

